version: '3.6'
services:
  freeipa:

    image: freeipa/freeipa-server:centos-8-stream
    hostname: ipa
    domainname: example.com
    container_name: freeipa
    # dns:
    #   - 8.8.8.8
    #   - 1.1.1.1
    # extra_hosts:
    #   - "ipa.example.com:127.0.0.1"
    restart: unless-stopped
    tty: true
    stdin_open: true
    privileged: true
    # read_only: true

    environment:
      - IPA_SERVER_HOSTNAME=ipa.example.com
      - IPA_SERVER_IP=127.0.0.1
      - PASSWORD=IN54N3LEYSTRONGPASSWORD
      # - DNS=127.0.0.11

    command:
      - -U
      - --domain=example.com
      - --realm=EXAMPLE.COM
      - --http-pin=IN54N3LEYSTRONGPASSWORD
      - --dirsrv-pin=IN54N3LEYSTRONGPASSWORD
      - --ds-password=IN54N3LEYSTRONGPASSWORD
      - --admin-password=IN54N3LEYSTRONGPASSWORD
      - --no-host-dns
      #- --no-dnssec-validation
      #- --setup-dns
      #- --auto-forwarders
      #- --allow-zone-overlap
      - --unattended

    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

    # networks:
    #   ipa:
    #     ipv4_address: 127.0.0.1

    volumes:
      - ./data:/data
      - ./logs:/var/logs
      # - /sys/fs/cgroup:/sys/fs/cgroup:ro

    tmpfs:
      - /run
      - /var/cache
      - /tmp

    cap_add:
      - SYS_TIME
      - NET_ADMIN

# networks:
#   ipa:
#     driver: bridge
#     driver_opts:
#       com.docker.network.driver.mtu: 1300
#     ipam:
#       config:
#         - subnet: "127.0.0.1/24"
